<?php
/**
 * Home #005 Template.
 *
 * @package Go_Plugin
 */

return array(
	array(
		'core/image',
		array(
			'url'             => GO_PLUGIN_URL . '/images/2x3.jpg',
			'alt'             => __( 'Image description', 'go-plugin' ),
			'caption'         => '',
			'linkDestination' => 'none',
			'className'       => 'size-full is-style-top-wave mb-0',
			'align'           => 'full',
			'noBottomMargin'  => true,
		),
		array(),
	),
	array(
		'core/gallery',
		array(
			'images'      => array(
				array(
					'url' => GO_PLUGIN_URL . '/images/1x1.jpg',
					'alt' => __( 'Image description', 'go-plugin' ),
					'id'  => 'home-image-2',
				),
				array(
					'url' => GO_PLUGIN_URL . '/images/1x1.jpg',
					'alt' => __( 'Image description', 'go-plugin' ),
					'id'  => 'home-image-3',
				),
			),
			'ids'         => array(),
			'caption'     => '',
			'imageCrop'   => true,
			'noTopMargin' => true,
			'linkTo'      => 'none',
			'sizeslug'    => 'large',
			'className'   => 'mt-0',
			'align'       => 'full',
		),
		array(),
	),
	array(
		'core/heading',
		array(
			'align'   => 'center',
			'content' => __( 'Welcome to Salt', 'go-plugin' ),
			'level'   => 2,
		),
		array(),
	),
	array(
		'core/paragraph',
		array(
			'align'   => 'center',
			'content' => __( 'For over forty years Salt has been known for its luxury lobster, steamed clams, barbecued chicken and homemade clam chowder. Stop on by and grab some of the most incredible seafood you\'ll ever taste.', 'go-plugin' ),
			'dropCap' => false,
		),
		array(),
	),
	array(
		'core/spacer',
		array(
			'height' => 30,
		),
		array(),
	),
	array(
		'core/heading',
		array(
			'align'   => 'center',
			'content' => __( 'Food &amp; Hours', 'go-plugin' ),
			'level'   => 3,
		),
		array(),
	),
	array(
		'coblocks/features',
		array(
			'paddingUnit'            => 'px',
			'paddingSize'            => 'no',
			'paddingSyncUnits'       => false,
			'paddingSyncUnitsTablet' => true,
			'paddingSyncUnitsMobile' => true,
			'marginUnit'             => 'px',
			'marginSize'             => 'no',
			'marginSyncUnits'        => false,
			'marginSyncUnitsTablet'  => false,
			'marginSyncUnitsMobile'  => false,
			'hasMarginControl'       => true,
			'hasAlignmentControls'   => true,
			'hasStackedControl'      => true,
			'backgroundType'         => 'image',
			'backgroundPosition'     => 'center center',
			'backgroundRepeat'       => 'no-repeat',
			'backgroundOverlay'      => 0,
			'hasParallax'            => false,
			'videoMuted'             => true,
			'videoLoop'              => true,
			'openPopover'            => false,
			'headingLevel'           => 4,
			'gutter'                 => 'large',
			'columns'                => 3,
			'contentAlign'           => 'center',
			'className'              => 'coblocks-features-818134018140',
			'align'                  => 'wide',
		),
		array(
			array(
				'coblocks/feature',
				array(
					'paddingUnit'            => 'px',
					'paddingSize'            => 'no',
					'paddingSyncUnits'       => false,
					'paddingSyncUnitsTablet' => true,
					'paddingSyncUnitsMobile' => true,
					'marginUnit'             => 'px',
					'marginSize'             => 'no',
					'marginSyncUnits'        => false,
					'marginSyncUnitsTablet'  => false,
					'marginSyncUnitsMobile'  => false,
					'hasMarginControl'       => true,
					'hasAlignmentControls'   => true,
					'hasStackedControl'      => true,
					'backgroundType'         => 'image',
					'backgroundPosition'     => 'center center',
					'backgroundRepeat'       => 'no-repeat',
					'backgroundOverlay'      => 0,
					'hasParallax'            => false,
					'videoMuted'             => true,
					'videoLoop'              => true,
					'openPopover'            => false,
					'headingLevel'           => 4,
					'className'              => 'coblocks-feature-818134018191',
				),
				array(
					array(
						'coblocks/icon',
						array(
							'icon'            => 'dining',
							'iconSize'        => 'medium',
							'hasContentAlign' => false,
							'iconColor'       => 'secondary',
							'height'          => 60,
							'width'           => 60,
							'borderRadius'    => 0,
							'padding'         => 0,
						),
						array(),
					),
					array(
						'core/heading',
						array(
							'content'     => __( 'Ocean to Plate', 'go-plugin' ),
							'level'       => 4,
							'placeholder' => __( 'Add feature title...', 'go-plugin' ),
						),
						array(),
					),
					array(
						'core/paragraph',
						array(
							'content' => __( 'Cajun &amp; creole seafood cuisine, never frozen - delish', 'go-plugin' ),
							'dropCap' => false,
						),
						array(),
					),
					array(
						'core/button',
						array(
							'text'            => __( 'See Menu', 'go-plugin' ),
							'backgroundColor' => 'secondary',
							'align'           => 'center',
						),
						array(),
					),
				),
			),
			array(
				'coblocks/feature',
				array(
					'paddingUnit'            => 'px',
					'paddingSize'            => 'no',
					'paddingSyncUnits'       => false,
					'paddingSyncUnitsTablet' => true,
					'paddingSyncUnitsMobile' => true,
					'marginUnit'             => 'px',
					'marginSize'             => 'no',
					'marginSyncUnits'        => false,
					'marginSyncUnitsTablet'  => false,
					'marginSyncUnitsMobile'  => false,
					'hasMarginControl'       => true,
					'hasAlignmentControls'   => true,
					'hasStackedControl'      => true,
					'backgroundType'         => 'image',
					'backgroundPosition'     => 'center center',
					'backgroundRepeat'       => 'no-repeat',
					'backgroundOverlay'      => 0,
					'hasParallax'            => false,
					'videoMuted'             => true,
					'videoLoop'              => true,
					'openPopover'            => false,
					'headingLevel'           => 4,
					'className'              => 'coblocks-feature-818134018197',
				),
				array(
					array(
						'coblocks/icon',
						array(
							'icon'            => 'waves',
							'iconSize'        => 'medium',
							'hasContentAlign' => false,
							'iconColor'       => 'secondary',
							'height'          => 60,
							'width'           => 60,
							'borderRadius'    => 0,
							'padding'         => 0,
						),
						array(),
					),
					array(
						'core/heading',
						array(
							'content'     => __( 'Dine with Us', 'go-plugin' ),
							'level'       => 4,
							'placeholder' => __( 'Add feature title...', 'go-plugin' ),
						),
						array(),
					),
					array(
						'core/paragraph',
						array(
							'content' => __( 'Mon - Thurs => 5pm - 11pm<br> Fri-Sat => 5pm - Midnight', 'go-plugin' ),
							'dropCap' => false,
						),
						array(),
					),
					array(
						'core/button',
						array(
							'text'            => __( 'Dine in', 'go-plugin' ),
							'backgroundColor' => 'secondary',
							'align'           => 'center',
						),
						array(),
					),
				),
			),
			array(
				'coblocks/feature',
				array(
					'paddingUnit'            => 'px',
					'paddingSize'            => 'no',
					'paddingSyncUnits'       => false,
					'paddingSyncUnitsTablet' => true,
					'paddingSyncUnitsMobile' => true,
					'marginUnit'             => 'px',
					'marginSize'             => 'no',
					'marginSyncUnits'        => false,
					'marginSyncUnitsTablet'  => false,
					'marginSyncUnitsMobile'  => false,
					'hasMarginControl'       => true,
					'hasAlignmentControls'   => true,
					'hasStackedControl'      => true,
					'backgroundType'         => 'image',
					'backgroundPosition'     => 'center center',
					'backgroundRepeat'       => 'no-repeat',
					'backgroundOverlay'      => 0,
					'hasParallax'            => false,
					'videoMuted'             => true,
					'videoLoop'              => true,
					'openPopover'            => false,
					'headingLevel'           => 4,
					'className'              => 'coblocks-feature-818134024141',
				),
				array(
					array(
						'coblocks/icon',
						array(
							'icon'            => 'scatter_plot',
							'iconSize'        => 'medium',
							'hasContentAlign' => false,
							'iconColor'       => 'secondary',
							'height'          => 60,
							'width'           => 60,
							'borderRadius'    => 0,
							'padding'         => 0,
						),
						array(),
					),
					array(
						'core/heading',
						array(
							'content'     => __( 'Catering', 'go-plugin' ),
							'level'       => 4,
							'placeholder' => __( 'Add feature title...', 'go-plugin' ),
						),
						array(),
					),
					array(
						'core/paragraph',
						array(
							'content'     => __( 'We cater all events from family reunions, to weddings', 'go-plugin' ),
							'dropCap'     => false,
							'placeholder' => __( 'Add feature content', 'go-plugin' ),
						),
						array(),
					),
					array(
						'core/button',
						array(
							'text'            => __( 'Contact', 'go-plugin' ),
							'backgroundColor' => 'secondary',
							'align'           => 'center',
						),
						array(),
					),
				),
			),
		),
	),
	array(
		'core/image',
		array(
			'url'             => GO_PLUGIN_URL . '/images/2x3.jpg',
			'alt'             => __( 'Image description', 'go-plugin' ),
			'caption'         => '',
			'linkDestination' => 'none',
			'className'       => 'size-large is-style-top-wave',
			'align'           => 'full',
		),
		array(),
	),
);
